# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7950d21b8724227e26443a59597664f06fb75ef0c3550d131679cafded06e287b323e197f31d4653ff53e39eaf29d5b2b31a70e943e4821af99d0e9540bf4951

test:
  secret_key_base: 557001157cae767af1472207656cb265bae8b8a99105931118e277449f56d5f6b3d99511e107558b8e3b145f00e4dfb03afba075e427b958191a26d14356589d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
